#comments
all:
  children:
    revature:
      hosts:
        revature3:
          ansible_host: 20.97.12.217
        revature2:
          ansible_host: 104.215.72.107
        revature4:
          ansible_host: 13.84.166.27
        revature5:
          ansible_host: 
      vars:
        ansible_ssh_private_key_file: ~/.ssh/2105-may24-devops-ubuntu-vm-1_key.pem
        ansible_user: michael
