---
#start a playbook with three dashes, (optionally) end with three dots
#optional, human-readable name.
- name: tests and setup
#pattern match to individual hosts or groups.
  hosts: revature
  tasks:
    - name: ping server
      ping:
    - name: installing python3
      package:
        name: python3
        state: present
    - name: installing python3-pip
      package:
        name: python3-pip
        state: present
    - name: installing venv
      package:
        name: python3-venv
    - name: installing git
      package:
        name: git
        state: present
  when: ansible_facts['os_family'] != "Windows"
  #well, gonna give up on windows for now.

- name: deploy application
  hosts: revature
  tasks:
  - name: git clone my repo
    ansible.builtin.git:
      repo: https://github.com/2105-may24-devops/michael-project0.git
      dest: ~/mdtest/
      single_branch: yes
      version: main
  - name: pip install requirements into venv
    pip:
      requirements: ~/mdtest/requirements.txt
      virtualenv: ~/mdtest/venv
      virtualenv_command: python -m venv


- name: build test files/config files, then test the code
  hosts: revature
  tasks: 
  - name: Run script in control node
    script: 
      cmd: ./tester.sh
      chdir: ~/mdtest/
  - name: fetch files from
    fetch:
      src: ~/mdtest/logs.txt
      dest: ./results/{{ ansible_hostname }}-{{ ansible_date_time['epoch'] }}.txt
      flat: yes

- name: cleanup by deleting base folder
  hosts: revature
  tasks:
  - name: delete the whole folder
    file:
      path: ~/mdtest/
      state: absent

    

...
