---
- name: build test files/config files, then test the code
  hosts: revature
  vars: 
    base_path: mdtest
  tasks: 
  - name: Copy necessary test files to destination
    copy: 
      src: ./tests/
      dest: ~/{{ base_path }}/tests/
  - name: Run script in control node
    script: 
      cmd: ./testscript.sh
      chdir: /home/{{ansible_user}}/{{ base_path }}/
    register: script_out
  - name: skipped debugging step, left in for future debugging
    ansible.builtin.debug:
      var: script_out
    when: False
  - name: fetch files from the remote
    fetch:
      src: ~/{{ base_path }}/tests/log.txt
      dest: ./results/log-{{ ansible_hostname }}-{{ ansible_date_time['epoch'] }}.txt
      flat: yes
    # with_fileglob:
    #   - ~/{{ base_path }}/tests/*
...
