---
#names are human-readable
- name: use git to get application code.
  hosts: revature3
  tasks:
  - name: git clone my repo. 
    #repo contents will end up in the folder specified by the dest, not as a subfolder in dest.
    ansible.builtin.git:
      repo: https://github.com/2105-may24-devops/michael-project0.git
      dest: ~/mdtest2/
      single_branch: yes
      version: main
  - name: pip install requirements into venv
    pip:
      requirements: ~/mdtest2/requirements.txt
      virtualenv: ~/mdtest2/venv
      virtualenv_command: python3 -m venv
      

# - name: Use SCP to copy code to hosts
# #pattern match to individual hosts or groups.
#   hosts: revature
#   vars:
#     user: michael
#   tasks:
#     - name: make a directory to work in.
#       file:
#         path: ~/ansible_MD_sandbox/
#         owner: "{{ user }}"

#     - name: Copy python files to destination.
#       copy:
#         src: "{{my_source}}"
#         dest: 
# copy: 
    #   src: ./tester.sh #TODO: build the tester script, as well as the test config files.
    #   dest: ~/mdtest/tester.sh 
    #   state: file
    #   mode: u=rwx,g=r,o=r #should be same as chmod 744